name: SYNC_CMS_to_Security
on: [push, pull_request]
env:
  GITHUB_TOKEN: "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"
jobs:
  SYNC_REPOS:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout_dst
      uses: actions/checkout@v2   
      with:
          repository: kaymatrix/actiontest2		      
          path: ./repodst
          token: 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
    - run: echo "Check out dst repo & initialize 1 sync..."
    - run: pwd
    - run: ls
    - run: echo "Test" > test.txt
      working-directory: ./repodst	
    - run: git add .
      working-directory: ./repodst	
    - run: git commit -m "done!"
      working-directory: ./repodst		  
    - run: git push
      working-directory: ./repodst 
      
    - run: echo "End"
