name: SYNC_CMS_to_Security
on: [push, pull_request]
jobs:
  SYNC_REPOS:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout_dst
      uses: actions/checkout@v2   
      with:          
          repository: kaymatrix/actiontest2
          path: ./repodst
          persist-credentials: false
          github_token: ${{ secrets.MYTOKEN }}
          
    - run: echo "Check out dst repo & initialize 1 sync..."
    - run: pwd
    - run: ls
    - run: git config user.name github-actions[bot]
    - run: git config user.email github-actions[bot]@users.noreply.github.com
    - run: echo "Test" > test.txt
      working-directory: ./repodst
    - run: ls
      working-directory: ./repodst
    - run: git remote set-url origin https://x-access-token:${{ secrets.MYTOKEN }}@github.com/kaymatrix/actiontest2.git
      working-directory: ./repodst
    - run: git add .
      working-directory: ./repodst
    - run: git commit -am "done!"
      working-directory: ./repodst      
    - run: git push
      working-directory: ./repodst
      
    - run: echo "End"
