name: SYNC_CMS_to_Security
on: [push, pull_request]

jobs:
  SYNC_REPOS:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout_dst
      uses: actions/checkout@v2   
      with:          
          repository: kaymatrix/actiontest
          path: ./repodst
    
    - run: pwd
    - run: ls
    - run: git config --global user.name 'kaymatrix'
    - run: git config --global user.email 'kaymatrix@gmail.com'
    - run: echo "Test" > test.txt
      working-directory: ./repodst
    - run: ls
      working-directory: ./repodst
    - run: git remote set-url origin "https://kaymatrix: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@github.com/kaymatrix/actiontest.git"
      working-directory: ./repodst
    - run: git add .
      working-directory: ./repodst
    - run: git commit -am "done!"
      working-directory: ./repodst      
    - run: git push
      working-directory: ./repodst
      
    - run: echo "End"
