name: SYNC_CMS_to_Security
on: [push, pull_request]
jobs:
  SYNC_REPOS:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout_dst
      uses: actions/checkout@v2   
      with:
          repository: kaymatrix/actiontest2
          path: ./repodst          
    - run: echo "Check out dst repo & initialize 1 sync...."
    - run: pwd
    - run: ls
    - run: git config --global user.email "kaymatrix@gmail.com"
    - run: git config --global user.name "kaymatrix"
    - run: echo "Test" > test.txt
      working-directory: ./repodst
    - run: ls
      working-directory: ./repodst
    - run: git remote set-url origin ssh://git@github.com/kaymatrix/actiontest2.git
      working-directory: ./repodst
    - run: git add .
      working-directory: ./repodst
    - run: git commit -m "done!"
      working-directory: ./repodst      
    - run: git push
      working-directory: ./repodst
      
    - run: echo "End"
